### ISSUE TITLE
TODO Port Patches

### ISSUE THREAD

**Issue by IsaiahPatton** [BukkitFabric/bukkit4fabric#10]
_* This list may be slightly off_
- [ ] Style (ChatModifier.patch)
- [x] WorldChunk (Chunk.patch)
- [ ] ChunkGenerator (ChunkGenerator.patch)
- [ ] NoiseChunkGenerator (ChunkGeneratorAbstract.patch)
- [ ] ChunkTicketManager (ChunkMapDistance.patch)
- [ ] ServerChunkManager (ChunkProviderServer.patch)
- [ ] ChunkStatus (ChunkStatus.patch)
- [ ] CommandBlockExecutor (CommandBlockListenerAbstract.patch)
- [ ] CommandManager (CommandDispatcher.patch)
- [x] ServerCommandSource (CommandListenerWrapper.patch)
- [ ] ScreenHandler (Container.patch)
- [ ] ScreenHandlerContext (ContainerAccess.patch)
- [ ] LevelStorage (Convertable.patch)
- [ ] RecipeManager (CraftingManager.patch)
- [ ] DamageSource (DamageSource.patch)
- [x] MinecraftDedicatedServer (DedicatedServer.patch)
- [ ] ServerPropertiesHandler (DedicatedServerProperties.patch)
- [ ] ServerPropertiesLoader (DedicatedServerSettings.patch)
- [ ] Bootstrap (DispenserRegistry.patch)
- [ ] PhaseManager (DragonControllerManager.patch)
- [ ] BanEntry (ExpirableListEntry.patch)
- [ ] Explosion (Explosion.patch)
- [ ] HungerManager (FoodMetaData.patch)
- [ ] GameRules (GameRules.patch)
- [ ] WorldAccess (GeneratorAccess.patch)
- [ ] ServerHandshakeNetworkHandler (HandshakeListener.patch)
- [ ] BlockView (IBlockAccess.patch)
- [ ] Text (IChatBaseComponent.patch)
- [ ] VersionedChunkStorage (IChunkLoader.patch)
- [x] CommandOutput (ICommandListener.patch)
- [ ] DispenserBehavior (IDispenseBehavior.patch)
- [ ] Angerable (IEntityAngerable.patch)
- [ ] EntityPredicates (IEntitySelector.patch)
- [x] Inventory (IInventory.patch)
- [ ] Trader (IMerchant.patch)
- [ ] ProjectileEntity (IProjectile.patch)
- [ ] ArmorItem (ItemArmor.patch)
- [ ] ArmorStandItem (ItemArmorStand.patch)
- [ ] BlockItem (ItemBlock.patch)
- [ ] ModifiableWorld (IWorldWriter.patch)
- [ ] ServerConfigList (JsonList.patch)
- [x] LegacyQueryHandler (LegacyPingHandler.patch)
- [x] ServerLoginNetworkHandler (LoginListener.patch)
- [x] MinecraftServer (MinecraftServer.patch)
- [ ] StatusEffect (MobEffectList.patch)
- [ ] StatusEffects (MobEffects.patch)
- [ ] ClientConnection (NetworkManager.patch)
- [ ] PacketByteBuf (PacketDataSerializer.patch)
- [ ] GuiCloseC2SPacket (PacketPlayInCloseWindow.patch)
- [ ] ChunkDeltaUpdateS2CPacket (PacketPlayOutMultiBlockChange.patch)
- [x] ServerQueryNetworkHandler (PacketStatusListener.patch)
- [ ] ChunkHolder (PlayerChunk.patch)
- [ ] ThreadedAnvilChunkStorage (PlayerChunkMap.patch)
- [x] ServerPlayNetworkHandler (PlayerConnection.patch)
- [ ] NetworkThreadUtils (PlayerConnectionUtils.patch)
- [ ] ServerPlayerInteractionManager (PlayerInteractManager.patch)
- [ ] PlayerInventory (PlayerInventory.patch)
- [x] PlayerManager (PlayerList.patch)
- [ ] PortalForcer (PortalTravelAgent.patch)
- [ ] AbstractPropertiesHandler (PropertyManager.patch)
- [ ] ServerScoreboard (ScoreboardServer.patch)
- [x] ServerNetworkIo (ServerConnection.patch)
- [ ] SpawnHelper (SpawnerCreature.patch)
- [ ] ChunkTicketType (TicketType.patch)
- [ ] ServerTickScheduler (TickListServer.patch)
- [ ] BlockEntity (TileEntity.patch)
- [ ] World (World.patch)
- [ ] ServerWorldAccess (WorldAccess.patch)
- [ ] WorldBorder (WorldBorder.patch)
- [x] LevelProperties (WorldDataServer.patch)
- [ ] MapState (WorldMap.patch)
- [x] WorldSaveHandler (WorldNBTStorage.patch)
- [x] ServerWorld (WorldServer.patch)
- [ ] WorldUpdater (WorldUpgrader.patch)
- [ ] Advancement (Advancement.patch)
- [ ] PlayerAdvancementTracker (AdvancementDataPlayer.patch)
- [ ] AdvancementManager (Advancements.patch)
- [ ] ForgetAttackTargetTask (BehaviorAttackTargetForget.patch)
- [ ] UpdateAttackTargetTask (BehaviorAttackTargetSet.patch)
- [ ] GoToWorkTask (BehaviorCareer.patch)
- [ ] FarmerVillagerTask (BehaviorFarm.patch)
- [ ] OpenDoorsTask (BehaviorInteractDoor.patch)
- [ ] VillagerBreedTask (BehaviorMakeLove.patch)
- [ ] LoseJobOnSiteLossTask (BehaviorProfession.patch)
- [ ] LookTargetUtil (BehaviorUtil.patch)
- [ ] FarmerWorkTask (BehaviorWorkComposter.patch)
- [ ] ReloadCommand (CommandReload.patch)
- [ ] SpreadPlayersCommand (CommandSpreadPlayers.patch)
- [ ] TeleportCommand (CommandTeleport.patch)
- [ ] TimeCommand (CommandTime.patch)
- [ ] EffectCommand (CommandEffect.patch)
- [ ] GameModeCommand (CommandGamemode.patch)
- [ ] BoatDispenserBehavior (DispenseBehaviorBoat.patch)
- [ ] ItemDispenserBehavior (DispenseBehaviorItem.patch)
- [ ] ProjectileDispenserBehavior (DispenseBehaviorProjectile.patch)
- [ ] ShearsDispenserBehavior (DispenseBehaviorShears.patch)
- [ ] BlockPlacementDispenserBehavior (DispenseBehaviorShulkerBox.patch)
- [ ] MobSpawnerLogic (MobSpawnerAbstract.patch)
- [ ] PillagerSpawner (MobSpawnerPatrol.patch)
- [ ] PhantomSpawner (MobSpawnerPhantom.patch)
- [ ] WanderingTraderManager (MobSpawnerTrader.patch)
- [ ] BannerBlockEntity (TileEntityBanner.patch)
- [ ] BarrelBlockEntity (TileEntityBarrel.patch)
- [ ] BeaconBlockEntity (TileEntityBeacon.patch)
- [ ] BeehiveBlockEntity (TileEntityBeehive.patch)
- [ ] BrewingStandBlockEntity (TileEntityBrewingStand.patch)
- [ ] CampfireBlockEntity (TileEntityCampfire.patch)
- [ ] ChestBlockEntity (TileEntityChest.patch)
- [ ] CommandBlockBlockEntity (TileEntityCommand.patch)
- [ ] ConduitBlockEntity (TileEntityConduit.patch)
- [ ] LockableContainerBlockEntity (TileEntityContainer.patch)
- [ ] DispenserBlockEntity (TileEntityDispenser.patch)
- [ ] EndGatewayBlockEntity (TileEntityEndGateway.patch)
- [ ] AbstractFurnaceBlockEntity (TileEntityFurnace.patch)
- [ ] HopperBlockEntity (TileEntityHopper.patch)
- [ ] ShulkerBoxBlockEntity (TileEntityShulkerBox.patch)
- [ ] SignBlockEntity (TileEntitySign.patch)
- [ ] BlastingRecipe (RecipeBlasting.patch)
- [ ] ServerRecipeBook (RecipeBookServer.patch)
- [ ] CampfireCookingRecipe (RecipeCampfire.patch)
- [ ] Ingredient (RecipeItemStack.patch)
- [ ] SmithingRecipe (RecipeSmithing.patch)
- [ ] SmokingRecipe (RecipeSmoking.patch)
- [ ] StonecuttingRecipe (RecipeStonecutting.patch)
- [ ] WorldBorderS2CPacket (PacketPlayOutWorldBorder.patch)
- [ ] LootContextParameters (LootContextParameters.patch)
- [ ] LootingEnchantLootFunction (LootEnchantFunction.patch)
- [ ] LootPoolEntry (LootEntryAbstract.patch)
- [ ] RandomChanceWithLootingLootCondition (LootItemConditionRandomChanceWithLooting.patch)
- [ ] SurvivesExplosionLootCondition (LootItemConditionSurvivesExplosion.patch)
- [ ] LootTable (LootTable.patch)
- [ ] LootManager (LootTableRegistry.patch)
- [ ] BoatItem (ItemBoat.patch)
- [ ] BowItem (ItemBow.patch)
- [ ] BucketItem (ItemBucket.patch)
- [ ] ChorusFruitItem (ItemChorusFruit.patch)
- [ ] CrossbowItem (ItemCrossbow.patch)
- [ ] DyeItem (ItemDye.patch)
- [ ] EggItem (ItemEgg.patch)
- [ ] EndCrystalItem (ItemEndCrystal.patch)
- [ ] EnderEyeItem (ItemEnderEye.patch)
- [ ] EnderPearlItem (ItemEnderPearl.patch)
- [ ] FireChargeItem (ItemFireball.patch)
- [ ] FishingRodItem (ItemFishingRod.patch)
- [ ] FlintAndSteelItem (ItemFlintAndSteel.patch)
- [ ] DecorationItem (ItemHanging.patch)
- [ ] LeadItem (ItemLeash.patch)
- [ ] MilkBucketItem (ItemMilkBucket.patch)
- [ ] MinecartItem (ItemMinecart.patch)
- [ ] SpawnEggItem (ItemMonsterEgg.patch)
- [ ] PotionItem (ItemPotion.patch)
- [ ] MusicDiscItem (ItemRecord.patch)
- [ ] SignItem (ItemSign.patch)
- [ ] SkullItem (ItemSkullPlayer.patch)
- [ ] SnowballItem (ItemSnowball.patch)
- [ ] ItemStack (ItemStack.patch)
- [ ] TridentItem (ItemTrident.patch)
- [ ] FilledMapItem (ItemWorldMap.patch)
- [ ] AnvilScreenHandler (ContainerAnvil.patch)
- [ ] ForgingScreenHandler (ContainerAnvilAbstract.patch)
- [ ] BeaconScreenHandler (ContainerBeacon.patch)
- [ ] BrewingStandScreenHandler (ContainerBrewingStand.patch)
- [ ] CartographyTableScreenHandler (ContainerCartography.patch)
- [ ] GenericContainerScreenHandler (ContainerChest.patch)
- [ ] Generic3x3ContainerScreenHandler (ContainerDispenser.patch)
- [ ] EnchantmentScreenHandler (ContainerEnchantTable.patch)
- [ ] AbstractFurnaceScreenHandler (ContainerFurnace.patch)
- [ ] GrindstoneScreenHandler (ContainerGrindstone.patch)
- [ ] HopperScreenHandler (ContainerHopper.patch)
- [ ] HorseScreenHandler (ContainerHorse.patch)
- [ ] LecternScreenHandler (ContainerLectern.patch)
- [ ] LoomScreenHandler (ContainerLoom.patch)
- [ ] MerchantScreenHandler (ContainerMerchant.patch)
- [ ] PlayerScreenHandler (ContainerPlayer.patch)
- [ ] ScreenHandlerType (Containers.patch)
- [ ] ShulkerBoxScreenHandler (ContainerShulkerBox.patch)
- [ ] SmithingScreenHandler (ContainerSmithing.patch)
- [ ] StonecutterScreenHandler (ContainerStonecutter.patch)
- [ ] CraftingScreenHandler (ContainerWorkbench.patch)
- [ ] EntitySelectorReader (ArgumentParserSelector.patch)
- [ ] ClampedEntityAttribute (AttributeRanged.patch)
- [ ] BiomeArray (BiomeStorage.patch)
- [ ] CommandBossBar (BossBattleCustom.patch)
- [ ] CraftingInventory (InventoryCrafting.patch)
- [ ] CraftingResultInventory (InventoryCraftResult.patch)
- [ ] EnderChestInventory (InventoryEnderChest.patch)
- [ ] DoubleInventory (InventoryLargeChest.patch)
- [ ] TraderInventory (InventoryMerchant.patch)
- [ ] SimpleInventory (InventorySubcontainer.patch)
- [ ] Structure (DefinedStructure.patch)
- [ ] StructureManager (DefinedStructureManager.patch)
- [ ] FrostWalkerEnchantment (EnchantmentFrostWalker.patch)
- [ ] Enchantments (Enchantments.patch)
- [ ] DamageEnchantment (EnchantmentWeaponDamage.patch)
- [ ] ItemInstanceTheFlatteningFix (DataConverterFlatten.patch)
- [ ] ItemInstanceMapIdFix (DataConverterMap.patch)
- [ ] Schemas (DataConverterRegistry.patch)
- [ ] DataTracker (DataWatcher.patch)
- [ ] FlowableFluid (FluidTypeFlowing.patch)
- [ ] LavaFluid (FluidTypeLava.patch)
- [ ] TeleportTarget (ShapeDetectorShape.patch)
- [ ] ShapedRecipe (ShapedRecipes.patch)
- [ ] ShapelessRecipe (ShapelessRecipes.patch)
- [ ] FurnaceOutputSlot (SlotFurnaceResult.patch)
- [ ] Raid (Raid.patch)
- [ ] RayTraceContext (RayTrace.patch)
- [ ] ChunkRegion (RegionLimitedWorldAccess.patch)
- [ ] RaidManager (PersistentRaid.patch)
- [ ] FeatureUpdater (PersistentStructureLegacy.patch)
- [ ] PiglinBrain (PiglinAI.patch)
- [ ] TradeOffer (MerchantRecipe.patch)
- [ ] Recipe (IRecipe.patch)
- [ ] SpecialCraftingRecipe (IRecipeComplex.patch)
- [ ] ZombieSiegeManager (VillageSiege.patch)
- [ ] RconCommandOutput (RemoteControlCommandListener.patch)
- [ ] SaddledComponent (SaddleStorage.patch)
- [ ] SmeltingRecipe (FurnaceRecipe.patch)
- [ ] CrashReport (CrashReport.patch)
- [ ] CommandFunctionManager (CustomFunctionData.patch)
- [ ] GameRuleCommand (CommandGamerule.patch)
- [ ] StatHandler (StatisticManager.patch)
- [ ] SaplingGenerator (WorldGenTreeProvider.patch)
- [ ] TextColor (ChatHexColor.patch)
