### ISSUE TITLE
TODO Events

### ISSUE THREAD

**Issue by pisaiah** [BukkitFabric/bukkit4fabric#9]
# Events
## Blocks
- [x] BlockBreakEvent
- [ ] BlockBurnEvent
- [x] BlockCanBuildEvent
- [ ] BlockCookEvent
- [x] BlockDamageEvent
- [x] BlockDispenseArmorEvent
- [ ] BlockDispenseEvent
- [ ] BlockDropItemEvent
- [ ] BlockExpEvent
- [x] BlockExplodeEvent
- [ ] BlockFadeEvent
- [ ] BlockFertilizeEvent
- [ ] BlockFormEvent
- [ ] BlockFromToEvent
- [ ] BlockGrowEvent
- [x] BlockIgniteEvent
- [ ] BlockMultiPlaceEvent
- [ ] BlockPhysicsEvent
- [x] BlockPistonEvent
- [x] BlockPistonExtendEvent
- [x] BlockPistonRetractEvent
- [x] BlockPlaceEvent
- [ ] BlockRedstoneEvent
- [x] BlockShearEntityEvent
- [ ] BlockSpreadEvent
- [ ] CauldronLevelChangeEvent
- [ ] EntityBlockFormEvent
- [ ] FluidLevelChangeEvent
- [x] LeavesDecayEvent
- [ ] MoistureChangeEvent
- [x] SignChangeEvent
- [ ] SpongeAbsorbEvent

## Entities
- [ ] AreaEffectCloudApplyEvent
- [x] #226
- [ ] CreatureSpawnEvent
- [x] CreeperPowerEvent
- [ ] EnderDragonChangePhaseEvent
- [x] EntityAirChangeEvent
- [x] EntityBreakDoorEvent
- [ ] EntityBreedEvent
- [ ] EntityChangeBlockEvent
- [ ] EntityCombustByBlockEvent
- [ ] EntityCombustByEntityEvent
- [ ] EntityCombustEvent
- [ ] EntityCreatePortalEvent
- [ ] EntityDamageByBlockEvent
- [ ] EntityDamageByEntityEvent
- [ ] EntityDamageEvent
- [x] EntityDeathEvent
- [x] EntityDropItemEvent
- [ ] EntityEnterBlockEvent
- [x] EntityEnterLoveModeEvent
- [x] EntityExplodeEvent
- [ ] EntityInteractEvent
- [ ] EntityPickupItemEvent
- [ ] EntityPlaceEvent
- [x] EntityPortalEnterEvent
- [ ] EntityPortalExitEvent
- [x] EntityPoseChangeEvent
- [ ] EntityPotionEffectEvent
- [x] EntityRegainHealthEvent
- [ ] EntityResurrectEvent
- [ ] EntityShootBowEvent
- [ ] EntitySpawnEvent
- [ ] EntitySpellCastEvent
- [ ] EntityTameEvent
- [ ] EntityTargetEvent
- [ ] EntityTargetLivingEntityEvent
- [ ] EntityTeleportEvent
- [ ] EntityToggleGlideEvent
- [ ] EntityToggleSwimEvent
- [ ] EntityTransformEvent
- [ ] EntityUnleashEvent
- [x] ExpBottleEvent
- [ ] ExplosionPrimeEvent
- [ ] FireworkExplodeEvent
- [ ] FoodLevelChangeEvent
- [x] HorseJumpEvent
- [x] ItemMergeEvent
- [ ] ItemDespawnEvent
- [ ] LingeringPotionSplashEvent
- [ ] PigZapEvent
- [x] PlayerDeathEvent
- [x] PlayerLeashEntityEvent
- [ ] ProjectileHitEvent
- [ ] ProjectileLaunchEvent

## Inventory
- [x] BrewEvent
- [x] BrewingStandFuelEvent
- [ ] CraftItemEvent
- [ ] Furnace Events (FurnaceBurnEvent, FurnaceExtractEvent, FurnaceSmeltEvent)
- [x] InventoryClickEvent
- [x] InventoryCloseEvent
- [ ] InventoryCreativeEvent
- [ ] InventoryDragEvent
- [ ] InventoryInteractEvent
- [ ] InventoryMoveItemEvent
- [x] InventoryOpenEvent
- [ ] InventoryPickupItemEvent
- [ ] PrepareAnvilEvent
- [x] PrepareItemCraftEvent
- [ ] PrepareSmithingEvent
- [ ] TradeSelectEvent

## Player
- [x] AsyncPlayerChatEvent
- [x] AsyncPlayerPreLoginEvent
- [x] PlayerAdvancementDoneEvent
- [x] PlayerAnimationEvent
- [x] PlayerArmorStandManipulateEvent
- [ ] Player Bed Events (PlayerBedEnterEvent & PlayerBedLeaveEvent)
- [x] Player Bucket Events (PlayerBucketEmptyEvent & PlayerBucketFillEvent)
- [x] PlayerChangedMainHandEvent
- [x] PlayerChangedWorldEvent
- [x] PlayerChatEvent
- [x] PlayerChatTabCompleteEvent
- [x] PlayerCommandPreprocessEvent
- [x] PlayerCommandSendEvent
- [x] PlayerDropItemEvent
- [ ] PlayerEditBookEvent
- [x] PlayerEggThrowEvent
- [x] PlayerExpChangeEvent
- [x] PlayerFishEvent
- [x] PlayerGameModeChangeEvent
- [ ] PlayerHarvestBlockEvent
- [ ] PlayerInteractAtEntityEvent
- [ ] PlayerInteractEntityEvent
- [x] PlayerInteractEvent
- [x] PlayerItemBreakEvent
- [x] PlayerItemConsumeEvent
- [x] PlayerItemDamageEvent
- [x] PlayerItemHeldEvent
- [x] PlayerItemMendEvent
- [x] PlayerJoinEvent
- [x] PlayerKickEvent
- [x] PlayerLevelChangeEvent
- [ ] PlayerLocaleChangeEvent
- [x] PlayerLoginEvent
- [x] PlayerMoveEvent
- [x] PlayerPickupArrowEvent
- [x] PlayerPickupItemEvent
- [ ] PlayerPortalEvent
- [x] PlayerPreLoginEvent
- [x] PlayerQuitEvent
- [ ] PlayerRecipeDiscoverEvent
- [x] PlayerRegisterChannelEvent
- [x] PlayerResourcePackStatusEvent
- [x] PlayerRespawnEvent
- [x] PlayerRiptideEvent
- [x] PlayerShearEntityEvent
- [x] PlayerSwapHandItemsEvent
- [x] PlayerTakeLecternBookEvent
- [ ] PlayerTeleportEvent
- [x] PlayerToggleFlightEvent
- [x] PlayerToggleSneakEvent
- [x] PlayerToggleSprintEvent
- [x] PlayerUnleashEntityEvent
- [x] PlayerUnregisterChannelEvent
- [ ] PlayerVelocityEvent

## Server
- [x] BroadcastMessageEvent
- [x] MapInitializeEvent
- [x] PluginDisableEvent
- [x] PluginEnableEvent
- [x] ServerCommandEvent
- [x] ServerListPingEvent
- [x] ServerLoadEvent
- [ ] ServiceRegisterEvent
- [ ] ServiceUnregisterEvent
- [x] TabCompleteEvent

## World
- [ ] Chunk Events (ChunkLoadEvent, ChunkPopulateEvent, ChunkUnloadEvent)
- [x] LootGenerateEvent
- [ ] PortalCreateEvent
- [x] SpawnChangeEvent
- [ ] StructureGrowEvent
- [x] TimeskipEvent
- [x] WorldInitEvent
- [x] WorldLoadEvent
- [x] WorldSaveEvent
- [x] WorldUnloadEvent

## Other
- [ ] Vehicle events
- [ ] Weather events
- [ ] hanging events
- [ ] enchantment events
- [ ] Raid Events

**Comment by SpiDrone** [comment]
Thanks for making a todo list, I'm really looking forward to your mod <3

**Comment by jLn0n** [comment]
2 years later and its still sh*t
